### ISSUE TITLE
Button to clear statistics

### ISSUE THREAD

**Issue by causticsudo** [gnome-pomodoro/gnome-pomodoro#606]
Hey, guys,

First off, thanks and congratulations for the wonderful app, today it's my favorite.

I wish there was a resource, to clear the time statistics I like in breaks and pomodoro, remaining time programmed.

Turns out in one day, I ended up suspending the laptop and forgetting to remove the long break, and this morning I went to look at the stats, and I just had 15hrs of break, lol.

Does it make sense to have a button to clear these stats?

**Comment by kamilprusko** [comment]
Hi @causticsudo  :)

Currently it counts suspended time or even reboots as if the timer was running. It's was a bad choice 😅 ... I'm doing thorough review of the timer internals. I intend to change it, so reboot/suspend would be counted as if the timer was paused.

As to adding a button to clear statistics -  i don't think it will be needed once the bug is fixed. Also, the project would benefit form a built-in time tracker. Ability to browse and edit history would make such button unnecessary.
